version: "3.7"
services:
  proyectos-backend-micro:
    container_name: proyectos-backend-micro
    image: proyectos-backend-micro:v1
    build:
      context: .
    ports:
      - 4002:8081
    networks:
      - proyectos-app

networks:
  proyectos-app: